[alias]
rel3="build --release --target=aarch64-unknown-none --no-default-features --features=raspi3b"
rel4="build --release --target=aarch64-unknown-none --no-default-features --features=raspi4"
run3="run --release --target=aarch64-unknown-none --no-default-features --features=raspi3b"
rundbg3="run --target=aarch64-unknown-none --no-default-features --features=raspi3b -- -S -s"
run="run --target=aarch64-unknown-none --no-default-features --features=raspi3b"
#run="run --release --target=aarch64-unknown-none --no-default-features --features=raspi4" # supported in next qemu version
img3="objcopy --release --target=aarch64-unknown-none --no-default-features --features=raspi3b -- -O binary out/kernel_bcm2837.img"
img4="objcopy --release --target=aarch64-unknown-none --no-default-features --features=raspi4 -- -O binary out/kernel_bcm2711.img"
inspect3="objdump --release --target=aarch64-unknown-none --no-default-features --features=raspi3b -- -h -f -s -S -C -d"
inspect4="objdump --release --target=aarch64-unknown-none --no-default-features --features=raspi4 -- -h -f -s -S -C -d"
inspectdbg3="objdump --target=aarch64-unknown-none --no-default-features --features=raspi3b -- -h -f -s -S -C -d"

[build]
target=["aarch64-unknown-none"]

[target.aarch64-unknown-none]
#runner="qemu-system-aarch64 -m 1G -M raspi3b -serial stdio -kernel "
runner="qemu-system-aarch64 -m 1G -M raspi3b -serial stdio -d int,mmu,unimp -kernel "
#runner="qemu-system-aarch64 -m 2G -M raspi4b -serial stdio -d int -kernel " # supported in next qemu version
rustflags=[
    "-C", "force-unwind-tables=no",
    "-C", "link-arg=-Tlink64.x",
# uncomment to strip symbols
#    "-C", "link-arg=-s",
    "-C", "target-feature=a53"
]