[alias]
rel="build --release"
run32="run --release --target=armv7a-none-eabi --no-default-features --features=raspi2b"
run64="run --release --target=aarch64-unknown-none --no-default-features --features=raspi3b"
imgpi3_32="objcopy --release --target=armv7a-none-eabi --no-default-features --features=raspi3b -- -O binary kernel7.img"
imgpi3_64="objcopy --release --target=aarch64-unknown-none --no-default-features --features=raspi3b -- -O binary kernel8.img"
imgpi4_32="objcopy --release --target=armv7a-none-eabi --no-default-features --features=raspi4 -- -O binary kernel7l.img"
imgpi4_64="objcopy --release --target=aarch64-unknown-none --no-default-features --features=raspi4 -- -O binary kernel8.img"
inspect64="objdump --release --target=aarch64-unknown-none -- -h -f -s -C"

[build]
target=["armv7a-none-eabi", "aarch64-unknown-none"]

[target.armv7a-none-eabi]
runner="qemu-system-arm -m 1G -M raspi2b -serial stdio -kernel"
rustflags=[
    "-C", "force-unwind-tables=false",
    "-C", "link-arg=-Tlink32.x",
    "-C", "link-arg=-s"
]

[target.aarch64-unknown-none]
runner="qemu-system-aarch64 -m 1G -M raspi3b -serial stdio -kernel"
rustflags=[
    "-C", "force-unwind-tables=false",
    "-C", "link-arg=-Tlink64.x",
    "-C", "link-arg=-s"
]