[alias]
rel="build --release"
run64="run --release --target=aarch64-unknown-none --no-default-features --features=raspi3b"
imgpi3_64="objcopy --release --target=aarch64-unknown-none --no-default-features --features=raspi3b -- -O binary kernel8.img"
imgpi4_64="objcopy --release --target=aarch64-unknown-none --no-default-features --features=raspi4 -- -O binary kernel8.img"
inspect64="objdump --release --target=aarch64-unknown-none -- -h -f -s -S -C -d"

[build]
target=["aarch64-unknown-none"]

[target.aarch64-unknown-none]
runner="qemu-system-aarch64 -m 1G -M raspi3b -serial stdio -kernel"
rustflags=[
    "-C", "force-unwind-tables=false",
    "-C", "link-arg=-Tlink64.x",
    "-C", "link-arg=-s",
    "-C", "target-feature=neon"
]